// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYbSlpa5Azv9EECrdRKOGu-eZgcZ-4wYo',
    appId: '1:923735631350:android:a02bf0ed063ac55b87d3d7',
    messagingSenderId: '923735631350',
    projectId: 'emandsdktest',
    databaseURL: 'https://emandsdktest.firebaseio.com',
    storageBucket: 'emandsdktest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCXGTL9RA-Qhmu50v1Yv9i8H8nxuGnHes',
    appId: '1:923735631350:ios:5f81d46ffbdf080587d3d7',
    messagingSenderId: '923735631350',
    projectId: 'emandsdktest',
    databaseURL: 'https://emandsdktest.firebaseio.com',
    storageBucket: 'emandsdktest.appspot.com',
    iosClientId:
        '923735631350-i3dv6o6de4i4em2kr3helkrpmjsqlqdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.onesignalFlutterSample',
  );
}
