name: "Setup Flutter"
description: "Sets up Flutter with the standard version for this repo"
runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: "3.35.5"
        cache: true
    - name: Install dependencies
      run: flutter pub get
      shell: bash
